name: 'Write for you by RaPa Learning'
description: 'Markdown and style linter'
inputs:
  markdown-options:
    description: 'Options to use while linting markdown'
    required: false
    default: '--ignore vale'
  known-words:
    description: 'Filename with known spellings'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup npm
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Setup linters
      run: 
        if [ ! -z "${{ inputs.known-words }}" ]; then
          echo "Taking in known words"
          cat "${{ inputs.known-words }}" >> /.github/styles/Vocab/Tooldoc/accept.txt
        fi

      shell: bash
    
    - name: Lint
      run: |
        npx jscpd --min-lines 3 --min-tokens 20 --threshold 0 --gitignore --ignore "**/*.yml"
        markdownlint --ignore vale --disable MD013 -- .
        markdown-link-check *.md
        # this will only check md files in the current directory.
        # because vale cannot ignore folders yet... and the vale README isn't compliant :)
        /vale/vale *.md
        echo "Check complete :)"
      shell: bash