name: Lint by inputting a repo url

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'Repository url (org/repo)'
        required: true
      known-words:
        description: 'Filename with known spellings'
        required: false
jobs:
  lint:
    runs-on: ubuntu-latest
    container: tartarite/repo4
    steps:
      - name: Clone
        uses: actions/checkout@main
        with:
          repository: ${{ github.event.inputs.URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        uses: Tartarite/write4u@docker-implementation
        with:
          known-words: ${{github.event.inputs.known-words}}



