name: Lint inputted repo

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'Repository url (org/repo)'
        required: true
      known-words:
        description: 'Filename with known spellings'
        required: false
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@main
        with:
          repository: ${{ github.event.inputs.URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print known words file
        run: echo ${{github.event.inputs.URL}}
      - name: Lint
        uses: RaPaLearning/write4u@main
        with:
          known-words: ${{github.event.inputs.URL}}


